name: Deploy

on:
  push:
    branches:
      - main

env:
  PRODUCTION: true

jobs:
  test-build-deploy:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
      - uses: actions/checkout@v3
      - uses: GuillaumeFalourd/setup-rsync@v1.1
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Create .env file
        run: echo "PORT=${{ secrets.API_PORT }}" > ./.env

      - name: Test SSH connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Delete OLD Folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            folder="${{secrets.HOME}}"
            if [ -d "$folder" ]; then
              rm -Rf ${{ secrets.HOME }}
            fi

      - name: Deploy with rsync
        run: |
          rsync --progress -avz -e "ssh -v -i ~/.ssh/id_rsa" \
          ./index.js \
          ./.env \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/

      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.HOME }}
            npm ci

      - name: Reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: systemctl reload nginx
